server:
  port: 9527
spring:
  application:
    name: gateway9527
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service           #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - MyType=gct
#            - Header=gct,zlq
#            - After=2024-03-11T22:11:20.903385200+08:00[Asia/Shanghai]
#            - Before=2024-03-11T22:20:20.903385200+08:00[Asia/Shanghai]
#            - Cookie=gct,zlq
#            - Host=**.atguigu.com
#            - Query=username, \d+  # 要有参数名username并且值还要是整数才能路由
#            - RemoteAddr=192.168.124.1/24 # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。


        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service               #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由



        - id: pay_routh3
          uri: lb://cloud-payment-service
          predicates:
#            - Path=/{gct}
#            - Path=/gateway/filter
            - Path=/pay/gateway/filter/**
          filters:
            - My=zlq
            #以下add在传递过来的时候，会失效，简而言之，会使用传递过来的值
#            - AddRequestHeader=gct,gct1 # 请求头kv，若一头含有多参则重写一行设置
#            - AddRequestHeader=zlq,zlq1
#            - RemoveRequestHeader=sec-fetch-site      # 删除请求头sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode,gct    # 将请求头sec-fetch-mode对应的值修改为gct
#            - AddRequestParameter=gct,9527001  # 新增请求参数Parameter：k ，v
#            - RemoveRequestParameter=zlq     # 删除url请求参数customerName，你传递过来也是null
#            - AddResponseHeader=gct,zlq # 新增回应头参数X-Response-atguigu并设值为BlueResponse
#            - SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
#            - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除
            #PrefixPath和SetPath不要混用
#            - PrefixPath=/pay      # http://localhost:9527/pay/gateway/filter
#            - SetPath=/pay/gateway/{gct}  # {segment}表示占位符，你写abc也行但要上下一致
#            - RedirectTo=302, http://www.baidu.com/ # 访问http://localhost:9527/pay/gateway/filter跳转到http://www.baidu.com/
#      default-filters: #全局配置


